version: '3'

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: administrator
    expose:
        - "5432"
    ports:
        - "5432:5432"
    network_mode: bridge